### ISSUE TITLE
multiple metrics with must and should requirements

### ISSUE THREAD

**Issue by cforce** [DataDog/watermarkpodautoscaler#100]
I read the doc and did not yet get an idea what happens if i would combine multiple metrics even of the same type
external and resource. 
What is possible and how will it behave? Given these examples

1.) 
I think i understood if you use type external  only one is allowed.
```
 - external:
      highWatermark: 400m
      lowWatermark: 150m
      metricName: custom.request_duration.max
      metricSelector:
        matchLabels:
          app: {{ .Chart.Name }}
          release: {{ .Release.Name }}
```

2.) But what if use resource? Can i have two metrics e.g. 
```
 - Resource:
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 85%
    type: Resource
- Resource:
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 90%
    type: Resource
```
And what happens if memory is at 90% and cpu at 50%? Will it scale up or down?

3.)  And if i even mix  kinds?
 - 1. prior never downscale based on mem but make sure memory stays below 85% always
 - 2. prio scale dynamically  based on cores utlization
Which one of a. and b. will full above requirement?

a.) 

```
 - external:
      highWatermark: 90
      lowWatermark: 60
      metricName: kubernetes.cpu.usage
      metricSelector:
        matchLabels:
          app: {{ .Chart.Name }}
          release: {{ .Release.Name }}
 - Resource:
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 85%
    type: Resource
```
b.)
```
 - external: 
      highWatermark: 85
      lowWatermark: 0
      metricName: kubernetes.ememoty.usage
      metricSelector:
        matchLabels:
          app: {{ .Chart.Name }}
          release: {{ .Release.Name }}
 - Resource:
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 85%
    type: Resource
```

4.) What if i mix and create contra dictionary  requirements

```
 - external:
      highWatermark: 80
      lowWatermark: 40
      metricName: kubernetes.cpu.usage
      metricSelector:
        matchLabels:
          app: {{ .Chart.Name }}
          release: {{ .Release.Name }}
- Resource:
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 90%
    type: Resource
```

**Comment by CharlyF** [comment]
Hello @cforce!
We are following the same design pattern as the upstream HPA, meaning that if you use several metrics the one that yields the greatest scaling event takes precedence.
As you can see [here](https://github.com/DataDog/watermarkpodautoscaler/blob/0a13d68d7a36a7fe8e0bf3e73977562f21aa9c3c/controllers/watermarkpodautoscaler_controller.go#L419) in the controller's code we loop over all of the metrics listed in the spec of a WPA (regardless of their type, to address your question about mixing types, it is supported). Then we keep the highest "recommendation" [here](https://github.com/DataDog/watermarkpodautoscaler/blob/0a13d68d7a36a7fe8e0bf3e73977562f21aa9c3c/controllers/watermarkpodautoscaler_controller.go#L518). We also take a conservative approach, in the case of a downscale, we will downscale to the highest recommendation (to prevent sudden large downscale as opposed to the upscale event).

> And what happens if memory is at 90% and cpu at 50%? Will it scale up or down?

it will scale to whatever is the highest number of replicas recommended given each metric compared to their watermarks and the current number of ready pods.

To address your last point, if one of the metric yields a scaling event, then it takes precedence even if we are within the bounds in the other one. This is because [we compare metrics independently](https://github.com/DataDog/watermarkpodautoscaler/blob/0a13d68d7a36a7fe8e0bf3e73977562f21aa9c3c/controllers/replica_calculator.go#L179-L217) to their watermarks.

Let us know if you have any more questions!

**Comment by cforce** [comment]
Thanks for clarifications so far.
Am i right i only can use one " - external:" metric entry but as much additional " "-Resource" metric 
That would mean i can not use the "watermark" features from external metric for different datadog metrics ate the same time or how shall i  fulfill  requirement from 3.) 

Is it a.) or b.) the another solution which works with externals from datadog for cpu and  mem (or any other metric)

Are my above examples generally   semantically correct?

**Comment by CharlyF** [comment]
You can use as many External or Resource entries and combination thereof as you wish.
So this is acceptable:

```
  - external:
    type: External
      highWatermark: 400m
      lowWatermark: 150m
      metricName: custom.request_duration.max
      metricSelector:
        matchLabels:
          kubernetes_cluster: mycluster
          service: billing
          short_image: billing-app
 - external:
    type: External
      highWatermark: 83
      lowWatermark: 21
      metricName: myothermetric.custom
      metricSelector:
        matchLabels:
          app: myapp
          release: 0.2.0
  - resource:
    type: Resource
      highWatermark: 300Mi
      lowWatermark: 50Mi
      name: memory
      metricSelector:
        matchLabels:
          app: nginx 
```

> Is it a.) or b.) the another solution which works with externals from datadog for cpu and mem (or any other metric)

Not sure if I fully grasp what you mean, but what I will say is, you can use multiple External types in a single WPA and you can mix with Resource types too. Resource types require the `/apis/metrics.k8s.io/` to be registered and serving (generally using the metrics server works out of the box) but you can find cpu or memory metrics that are collected by the Datadog Agents and therefore use External types to have the same value and as such, not need both the external metrics server (Datadog Cluster Agent) and the resource metrics server (metrics server), just the former.

I hope that answers your question. 

> Are my above examples generally semantically correct?

If you make sure to use a metric that exists in your Datadog account as an External type and also I think you would need to add
```
    type: External
```
in the `external` entry as above.
Then it should be okay.
