### ISSUE TITLE
docs: external_metrics vs custometric

### ISSUE THREAD

**Issue by cforce** [DataDog/watermarkpodautoscaler#103]
Trying to understand the difference or historical evolution?  from A.) external_metrics with embedded query as part of the wpa resource spec to  B.) external_metrics  referencing custom metric defined as dedicated 

A.)
```
apiVersion: datadoghq.com/v1alpha1
kind: WatermarkPodAutoscaler
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  metrics:
    - type: External
      external:
      metricName: "<METRIC_NAME>"
      metricSelector:
        matchLabels:
          <TAG_KEY>: <TAG_VALUE>

```
B.)

```
apiVersion: datadoghq.com/v1alpha1
kind: DatadogMetric
metadata:
  name: your_datadogmetric_name
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels" . | indent 4 }}
spec:
  query: avg:kubernetes.cpu.usage{app:myapp,release:myapp}.rollup(30)
```

```
apiVersion: datadoghq.com/v1alpha1
kind: WatermarkPodAutoscaler
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  metrics:
    - type: External
      external:
        metricName: "datadogmetric@{{ .Release.Namespace }}:your_datadogmetric_name"
```        

https://docs.datadoghq.com/agent/cluster_agent/external_metrics/#set-up-an-hpa-to-use-a-datadogmetric-object

1.) Is it like that B is the new version to spec metrics used in wpa instead of A since  Kubernetes v1.2  allows such?
2.) Why does B outweights A, in features, does it? Is A no longer best practice or even to be sundowned?
3.) Can instead defining a emtric resource via k8 manifest also use the beta datadog ui feature to create custom metric as "your_datadogmetric_name" and it is then referenceable in any wpa resource spec as well?
4.) If i change  the query live in ui for an already depliyed wpa using it, how fast will it be pulled?
5.) Does the in the query used "labels" will match always to the label i specified on the application i want to apply the metric filter on (e.g deployemnt.metadata.labels ?
6.) Creating new custom metric either via UI or k8 manifest - which tags can they filter on (e.g pods, deployments, deamons set)
