### ISSUE TITLE
Resource type WPA metrics do not appear to be averaging correctly

### ISSUE THREAD

**Issue by evan-underdog** [DataDog/watermarkpodautoscaler#153]
**Describe what happened:**
Resource type WPA metrics do not appear to be calculating average values, rather they are calculating totals.

**Describe what you expected:**
I expect the values to be averaged.

```
> k top pod
NAME                                       CPU(cores)   MEMORY(bytes)   
ingress-nginx-controller-64dd76d79-lfckl   7m           122Mi           
ingress-nginx-controller-64dd76d79-rzxvc   8m           124Mi           
 
> k describe wpa nginx-wpa | grep -A 1 "Current Average Value"
      Current Average Value:  16m
      Name:                   cpu
--
      Current Average Value:  258920448
      Name:                   memory
```

**Comment by CharlyF** [comment]
👋  Hello @evan-underdog - Could you share the spec of the WPA you are using?

**Comment by evan-underdog** [comment]
@CharlyF yep should have included that initially:
```
spec:
  downscaleForbiddenWindowSeconds: 120
  upscaleForbiddenWindowSeconds: 30
  scaleDownLimitFactor: 25
  scaleUpLimitFactor: 50
  minReplicas: 2
  maxReplicas: 8
  scaleTargetRef:
    kind: "Deployment"
    name: "ingress-nginx-controller"
    apiVersion: "apps/v1"
  metrics:
  - external:
      highWatermark: 50
      lowWatermark: 0
      metricName: nginx.net.request_per_s
      metricSelector:
        matchLabels:
          env: staging
    type: External
  - resource:
      highWatermark: 400m
      name: cpu
      metricSelector:
        matchLabels:
          app: ingress-nginx
    type: Resource
  - resource:
      highWatermark: 500Mi
      name: memory
      metricSelector:
        matchLabels:
          app: ingress-nginx
    type: Resource
```
