### ISSUE TITLE
WPA controller was unable to update the number of replicas: status.currentMetrics in body must be of type array: "null"

### ISSUE THREAD

**Issue by deiga** [DataDog/watermarkpodautoscaler#54]
Hello 👋 

We're trying to take the WPA into use, but we keep seeing this error message:

```
{
	"level": "error",
	"ts": 1594040003.47035,
	"logger": "wpa_controller",
	"msg": "The WPA controller was unable to update the number of replicas",
	"Request.Namespace": "web-services-staging",
	"Request.Name": "nextapi",
	"error": "WatermarkPodAutoscaler.datadoghq.com \"nextapi\" is invalid: []: Invalid value: map[string]interface {}{\"apiVersion\":\"datadoghq.com/v1alpha1\", \"kind\":\"WatermarkPodAutoscaler\", \"metadata\":map[string]interface {}{\"annotations\":map[string]interface {}{\"meta.helm.sh/release-name\":\"nextapi\", \"meta.helm.sh/release-namespace\":\"web-services-staging\"}, \"creationTimestamp\":\"2020-07-06T12:49:21Z\", \"generation\":2, \"labels\":map[string]interface {}{\"app\":\"nextapi\", \"app.kubernetes.io/managed-by\":\"Helm\", \"chart\":\"mozart-0.4.0\", \"env\":\"staging\", \"heritage\":\"Helm\", \"region\":\"eu-west-1\", \"release\":\"nextapi\", \"stage\":\"staging\"}, \"name\":\"nextapi\", \"namespace\":\"web-services-staging\", \"resourceVersion\":\"124372418\", \"uid\":\"51196075-0345-4839-8526-3cf805be0376\"}, \"spec\":map[string]interface {}{\"algorithm\":\"absolute\", \"downscaleForbiddenWindowSeconds\":60, \"maxReplicas\":50, \"metrics\":[]interface {}{map[string]interface {}{\"external\":map[string]interface {}{\"highWatermark\":\"1\", \"lowWatermark\":\"0\", \"metricName\":\"php_fpm.listen_queue.size\", \"metricSelector\":map[string]interface {}{\"matchLabels\":map[string]interface {}{\"app\":\"nextapi\", \"region\":\"eu-west-1\", \"stage\":\"staging\"}}}, \"type\":\"External\"}}, \"minReplicas\":2, \"scaleDownLimitFactor\":30, \"scaleTargetRef\":map[string]interface {}{\"apiVersion\":\"apps/v1\", \"kind\":\"Deployment\", \"name\":\"nextapi\"}, \"scaleUpLimitFactor\":50, \"tolerance\":0.01, \"upscaleForbiddenWindowSeconds\":30}, \"status\":map[string]interface {}{\"conditions\":[]interface {}{map[string]interface {}{\"lastTransitionTime\":\"2020-07-06T12:53:23Z\", \"message\":\"Scaling changes can be applied\", \"reason\":\"DryRun mode disabled\", \"status\":\"False\", \"type\":\"DryRun\"}, map[string]interface {}{\"lastTransitionTime\":\"2020-07-06T12:53:23Z\", \"message\":\"the WPA controller was able to get the target's current scale\", \"reason\":\"SucceededGetScale\", \"status\":\"True\", \"type\":\"AbleToScale\"}, map[string]interface {}{\"lastTransitionTime\":\"2020-07-06T12:53:23Z\", \"message\":\"the HPA was unable to compute the replica count: unable to get external metric web-services-staging/php_fpm.listen_queue.size/&LabelSelector{MatchLabels:map[string]string{app: nextapi,region: eu-west-1,stage: staging,},MatchExpressions:[],}: unable to fetch metrics from external metrics API: the server is currently unable to handle the request (get php_fpm.listen_queue.size.external.metrics.k8s.io)\", \"reason\":\"FailedGetExternalMetric\", \"status\":\"False\", \"type\":\"ScalingActive\"}}, \"currentMetrics\":interface {}(nil), \"currentReplicas\":2, \"desiredReplicas\":0}}: validation failure list:\nstatus.currentMetrics in body must be of type array: \"null\"",
	"stacktrace": "github.com/go-logr/zapr.(*zapLogger).Error\n\twatermarkpodautoscaler/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/DataDog/watermarkpodautoscaler/pkg/controller/watermarkpodautoscaler.(*ReconcileWatermarkPodAutoscaler).reconcileWPA\n\twatermarkpodautoscaler/pkg/controller/watermarkpodautoscaler/watermarkpodautoscaler_controller.go:428\ngithub.com/DataDog/watermarkpodautoscaler/pkg/controller/watermarkpodautoscaler.(*ReconcileWatermarkPodAutoscaler).Reconcile\n\twatermarkpodautoscaler/pkg/controller/watermarkpodautoscaler/watermarkpodautoscaler_controller.go:344\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\twatermarkpodautoscaler/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:216\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\twatermarkpodautoscaler/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:192\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\twatermarkpodautoscaler/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:171\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\twatermarkpodautoscaler/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\twatermarkpodautoscaler/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\twatermarkpodautoscaler/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"
}

```

This is our WPA definition:
```
apiVersion: datadoghq.com/v1alpha1
kind: WatermarkPodAutoscaler
metadata:
  name: nextapi
  labels:
    app: nextapi
    chart: mozart-0.4.0
    release: nextapi
    heritage: Helm
    env: staging
    region: eu-west-1
    stage: staging
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nextapi
  downscaleForbiddenWindowSeconds: 60
  upscaleForbiddenWindowSeconds: 30
  scaleDownLimitFactor: 30
  scaleUpLimitFactor: 50
  minReplicas: 2
  maxReplicas: 50
  metrics:
    - external:
        highWatermark: "1"
        lowWatermark: "0"
        metricName: php_fpm.listen_queue.size
        metricSelector:
          matchLabels:
            app: nextapi
            stage: staging
            region: eu-west-1
      type: External
  tolerance: 0.01
```
