### ISSUE TITLE
WPA will get panic if we try to scale Openshift DeploymentConfig

### ISSUE THREAD

**Issue by yummydsky** [DataDog/watermarkpodautoscaler#69]
**Describe what happened:**
WPA try to scale-out Openshift DeploymentConfig but get the following error
```
{"level":"info","ts":1600848500.4110653,"logger":"wpa_controller","msg":"Reconciling WatermarkPodAutoscaler","Request.Namespace":"nginx-preloader-sample","Request.Name":"wpa4"}
{"level":"error","ts":1600848500.412769,"logger":"wpa_controller","msg":"RunTime error in reconcileWPA","Request.Namespace":"nginx-preloader-sample","Request.Name":"wpa4","returnValue":"runtime error: invalid memory address or nil pointer dereference","error":"recover error","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\twatermarkpodautoscaler/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/DataDog/watermarkpodautoscaler/pkg/controller/watermarkpodautoscaler.(*ReconcileWatermarkPodAutoscaler).reconcileWPA.func1\n\twatermarkpodautoscaler/pkg/controller/watermarkpodautoscaler/watermarkpodautoscaler_controller.go:360\nruntime.gopanic\n\t/usr/local/Cellar/go/1.13.4/libexec/src/runtime/panic.go:679\nruntime.panicmem\n\t/usr/local/Cellar/go/1.13.4/libexec/src/runtime/panic.go:199\nruntime.sigpanic\n\t/usr/local/Cellar/go/1.13.4/libexec/src/runtime/signal_unix.go:394\ngithub.com/DataDog/watermarkpodautoscaler/pkg/controller/watermarkpodautoscaler.(*ReconcileWatermarkPodAutoscaler).reconcileWPA\n\twatermarkpodautoscaler/pkg/controller/watermarkpodautoscaler/watermarkpodautoscaler_controller.go:379\ngithub.com/DataDog/watermarkpodautoscaler/pkg/controller/watermarkpodautoscaler.(*ReconcileWatermarkPodAutoscaler).Reconcile\n\twatermarkpodautoscaler/pkg/controller/watermarkpodautoscaler/watermarkpodautoscaler_controller.go:344\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\twatermarkpodautoscaler/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:216\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\twatermarkpodautoscaler/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:192\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\twatermarkpodautoscaler/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:171\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\twatermarkpodautoscaler/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\twatermarkpodautoscaler/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\twatermarkpodautoscaler/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
```

WPA.yaml
```
apiVersion: datadoghq.com/v1alpha1
kind: WatermarkPodAutoscaler
metadata:
  name: wpa4
  namespace: nginx-preloader-sample
spec:
  algorithm: average
  maxReplicas: 20
  minReplicas: 1
  tolerance: 0.01
  downscaleForbiddenWindowSeconds: 300
  upscaleForbiddenWindowSeconds: 15
  scaleUpLimitFactor: 90
  scaleDownLimitFactor: 90
  scaleTargetRef:
    kind: DeploymentConfig
    apiVersion: apps.openshift.io/v1
    name: nginx-prepared
  readinessDelay: 10
  metrics:
  - type: External
    external:
      highWatermark: "1"
      lowWatermark: "1"
      metricName: federatorai.recommendation
      metricSelector:
        matchLabels:
          resource: replicas
          kube_cluster: jason-4-115
          oshift_deployment_config: nginx-prepared
          kube_namespace: nginx-preloader-sample
```

Cluster Agent can get external metrics
```
  * watermark pod autoscaler: nginx-preloader-sample/wpa4
    Metric name: federatorai.recommendation
    Labels:
    - kube_cluster: jason-4-115
    - kube_namespace: nginx-preloader-sample
    - oshift_deployment_config: nginx-prepared
    - resource: replicas
    Value: 6
    Timestamp: 2020-09-23 08:18:00.000000 UTC
    Valid: true
```

Other WPA works as we expected
```
  * watermark pod autoscaler: myproject/wpa3
    Metric name: federatorai.recommendation
    Labels:
    - kube_cluster: jason-4-115
    - kube_deployment: consumer3
    - kube_namespace: myproject
    - resource: replicas
    Value: 7
    Timestamp: 2020-09-23 08:25:00.000000 UTC
    Valid: true
```

WPA yaml
```
apiVersion: datadoghq.com/v1alpha1
kind: WatermarkPodAutoscaler
metadata:
  name: wpa3
  namespace: myproject
spec:
  # Add fields here
  # algorithm must be average
  algorithm: average
  maxReplicas: 15
  minReplicas: 1
  tolerance: 0.01
  downscaleForbiddenWindowSeconds: 300
  upscaleForbiddenWindowSeconds: 15
  scaleUpLimitFactor: 90
  scaleDownLimitFactor: 90
  scaleTargetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: consumer3
  readinessDelay: 10
  metrics:
  # Resource or External type supported
  # Example usage of External type
  - type: External
    external:
      # do not edit highWatermakr, and lowWatermark
      # highWatermark and lowWatermark must be 1
      highWatermark: "1"
      lowWatermark: "1"
      metricName: federatorai.recommendation
      metricSelector:
        matchLabels:
          resource: replicas
          kube_cluster: jason-4-115
          kube_deployment: consumer3
          kube_namespace: myproject
```

WPA log
```
{"level":"info","ts":1600849222.9556293,"logger":"wpa_controller","msg":"Successful rescale","Request.Namespace":"myproject","Request.Name":"wpa3","currentReplicas":6,"desiredReplicas":7,"rescaleReason":"federatorai.recommendation{map[kube_cluster:jason-4-115 kube_deployment:consumer3 kube_namespace:myproject resource:replicas]} above target"}
```

**Describe what you expected:**
WPA can scale-out Openshift DeploymentConfig successfully.

**Steps to reproduce the issue:**

**Additional environment details (Kubernetes version, etc):**
openshift v3.11.0+8f721f2-450
kubernetes v1.11.0+d4cacc0

WPA image
image: datadog/watermarkpodautoscaler:v0.1.0
